### ISSUE TITLE
IRB Exempt Request

### ISSUE THREAD

**Issue by aaronducote** [Torin-Perkins/revolutionizing-higher-ed-rankings#1]
Send IRB Exempt Request for sending questionnaires and have it accepted by Oregon State University

**Comment by Elliot-Foley** [comment]
Worked on figuring out the form process. There are a number of steps which we need to complete:
Submitting a new IRB application: https://research.oregonstate.edu/irb-9
Presubmission process:
1) We need a Principle Investigator. They must have an OSU appointment (be an OSU employee) and be working within the scope of their research. Maybe this can be Fuxin?
2) Everyone involved in the study must complete the Online Ethics Training Module.
3) Create a consent/assent document or guide: https://research.oregonstate.edu/irb/resources-consent-and-assent-process/guidance-and-sample-language-consent-and-assent-documents
We also will need to include all the "recruitment materials" that we are going to use. Importantly, our emails must include: the title of the sudy, the name of the Principle Investigator, a clear statment that this is research or a studty, and contact information (the last part might not be needed, since they will be communicating via the form).
4) If we need help, we can request a remote advising session.
5) Not relevant for us, since we are not handling Level 3 data (ours is Level 2 at most)
6) Not relevant for us.
7) Not relevant for us, we have no financial conflicts of interest.
8) Not relevant for us, we are not transferring biological materials.
9) Not relevant for us, we only need the bare minimum to get past the door.

Submission process:
I can handle this, it's just submitting some forms it looks like

I have also sent an email to the IRB email address, asking for clarification on the exact requirements of what trainings we'll need to complete, as well as the requirements for being a PI, and also if we could set up an appointment with them if there's a lot to explain.

**Comment by Elliot-Foley** [comment]
Completed the "Responsible Conduct for Engineers" module in CITI, a prerequisite for filling out an IRB exemption form.

**Comment by Elliot-Foley** [comment]
Completed the other prerequisite CITI module, then completed the form except for the "Study Instruments" attachment section, which requires the form which we will send out. I reached out to Rhea at 2 on 11/11 asking for the final version of the form, but she has not yet responded.

**Comment by Elliot-Foley** [comment]
Sent completed exemption document to Fuxin for review

**Comment by Elliot-Foley** [comment]
Reworked specific sections according to our new methodology, and submitted the form for PI review on Cayuse

**Comment by Elliot-Foley** [comment]
Exemption request was approved as of January 12, 2024
